name: Deploy CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Create .env file
        run: |
          echo "${{ secrets.secrets}}" > .env
      - name: Sync code to application directory
        run: |
          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '.gitignore' \
            --exclude 'README.md' \
            --exclude '.github' \
            --exclude 'logs' \
            ./ /var/www/maki-backend/
      - name: Install dependencies in app directory
        working-directory: /var/www/maki-backend
        run: npm ci
      - name: Install PM2 globally if not present
        run: |
          if ! command -v pm2 &> /dev/null; then
            npm install pm2 -g
          fi
      - name: Deploy with PM2
        working-directory: /var/www/maki-backend
        run: |
              # Use reload which handles both cases gracefully
              pm2 reload ecosystem.config.cjs --env production || pm2 start ecosystem.config.cjs --env production
              pm2 save
